/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class getapkinfo_example_com_getapkinfo_JNIUtils */

#ifndef _Included_getapkinfo_example_com_getapkinfo_JNIUtils
#define _Included_getapkinfo_example_com_getapkinfo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     getapkinfo_example_com_getapkinfo_JNIUtils
 * Method:    getSignature
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_getapkinfo_example_com_getapkinfo_JNIUtils_getSignature
  (JNIEnv *, jclass, jobject);

/*
 * Class:     getapkinfo_example_com_getapkinfo_JNIUtils
 * Method:    getPackname
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_getapkinfo_example_com_getapkinfo_JNIUtils_getPackname
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
